package ec.dalara.factucore.domain.workflow;

public enum EstadoProceso {

	RECIBIDO, VALIDADO, SECUENCIAL_ASIGNADO, CLAVE_ACCESO_GENERADA, XML_GENERADO, XSD_VALIDADO, FIRMADO, ENVIADO_SRI,
	AUTORIZACION_PENDIENTE, AUTORIZACION_SRI, RIDE_GENERADO, NOTIFICACION_PUBLICADA
}
