package ec.dalara.factucore.domain.workflow;

public enum EtapaWorkflow {

	RECEPCION, VALIDACION, ASIGNACION_SECUENCIAL, GENERACION_CLAVE_ACCESO, GENERACION_XML, VALIDACION_XSD,
	FIRMA_ELECTRONICA, ENVIO_SRI, AUTORIZACION_SRI, GENERACION_RIDE, NOTIFICACION
}