# ============================================================
# FACTUCORE - CONFIGURACION EXTERNA
# ============================================================

spring.application.name=factucore-api

# ------------------------------------------------------------
# SERVER
# ------------------------------------------------------------

server.port=8088
server.servlet.context-path=/factucore-api


# ------------------------------------------------------------
# POSTGRESQL
# ------------------------------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5432/feFactuCore
spring.datasource.username=usr_factucore
spring.datasource.password=usr_factucore

spring.datasource.driver-class-name=org.postgresql.Driver


# ------------------------------------------------------------
# HIKARI
# ------------------------------------------------------------

spring.datasource.hikari.pool-name=FactuCoreHikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# ------------------------------------------------------------
# JPA / HIBERNATE
# ------------------------------------------------------------

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil


# ------------------------------------------------------------
# FLYWAY
# ------------------------------------------------------------

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true


# ------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------

logging.level.root=INFO
logging.level.com.dalara.factucore=INFO
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=INFO


# ------------------------------------------------------------
# FACTUCORE - DIRECTORIOS EXTERNOS
# ------------------------------------------------------------

factucore.path.base=C:/FactuCore
factucore.path.config=C:/FactuCore/config
factucore.path.certificados=C:/FactuCore/certificados
factucore.path.jasper=C:/FactuCore/jasper
factucore.path.documentos=C:/FactuCore/documentos
factucore.path.documentos.xml=C:/FactuCore/documentos/xml
factucore.path.documentos.pdf=C:/FactuCore/documentos/pdf
factucore.path.logs=C:/FactuCore/logs