package ec.dalara.factucore.domain.shared;

public final class MessageCodes {

    public static final String EMPRESA_RUC_REQUERIDO =
            "FACTUCORE.EMPRESA.RUC.REQUERIDO";

    public static final String EMPRESA_RAZON_SOCIAL_REQUERIDA =
            "FACTUCORE.EMPRESA.RAZON_SOCIAL.REQUERIDA";

    public static final String EMPRESA_DIRECCION_MATRIZ_REQUERIDA =
            "FACTUCORE.EMPRESA.DIRECCION_MATRIZ.REQUERIDA";

    public static final String RUC_REQUERIDO =
            "FACTUCORE.RUC.REQUERIDO";

    public static final String RUC_FORMATO_INVALIDO =
            "FACTUCORE.RUC.FORMATO_INVALIDO";

    public static final String ESTABLECIMIENTO_EMPRESA_REQUERIDA =
            "FACTUCORE.ESTABLECIMIENTO.EMPRESA.REQUERIDA";

    public static final String ESTABLECIMIENTO_CODIGO_REQUERIDO =
            "FACTUCORE.ESTABLECIMIENTO.CODIGO.REQUERIDO";

    public static final String PUNTO_EMISION_ESTABLECIMIENTO_REQUERIDO =
            "FACTUCORE.PUNTO_EMISION.ESTABLECIMIENTO.REQUERIDO";

    public static final String PUNTO_EMISION_CODIGO_REQUERIDO =
            "FACTUCORE.PUNTO_EMISION.CODIGO.REQUERIDO";

    public static final String SECUENCIAL_PUNTO_EMISION_REQUERIDO =
            "FACTUCORE.SECUENCIAL.PUNTO_EMISION.REQUERIDO";

    public static final String SECUENCIAL_CODIGO_DOCUMENTO_REQUERIDO =
            "FACTUCORE.SECUENCIAL.CODIGO_DOCUMENTO.REQUERIDO";

    public static final String SECUENCIAL_VALOR_INVALIDO =
            "FACTUCORE.SECUENCIAL.VALOR.INVALIDO";

    public static final String SECUENCIAL_LIMITE_ALCANZADO =
            "FACTUCORE.SECUENCIAL.LIMITE_ALCANZADO";

    public static final String NUMERO_COMPROBANTE_REQUERIDO =
            "FACTUCORE.NUMERO_COMPROBANTE.REQUERIDO";

    public static final String NUMERO_COMPROBANTE_FORMATO_INVALIDO =
            "FACTUCORE.NUMERO_COMPROBANTE.FORMATO_INVALIDO";

    public static final String CLAVE_ACCESO_REQUERIDA =
            "FACTUCORE.CLAVE_ACCESO.REQUERIDA";

    public static final String CLAVE_ACCESO_FORMATO_INVALIDO =
            "FACTUCORE.CLAVE_ACCESO.FORMATO_INVALIDO";

    public static final String COMPROBANTE_EMPRESA_REQUERIDA =
            "FACTUCORE.COMPROBANTE.EMPRESA.REQUERIDA";

    public static final String COMPROBANTE_ESTABLECIMIENTO_REQUERIDO =
            "FACTUCORE.COMPROBANTE.ESTABLECIMIENTO.REQUERIDO";

    public static final String COMPROBANTE_PUNTO_EMISION_REQUERIDO =
            "FACTUCORE.COMPROBANTE.PUNTO_EMISION.REQUERIDO";

    public static final String COMPROBANTE_CODIGO_DOCUMENTO_REQUERIDO =
            "FACTUCORE.COMPROBANTE.CODIGO_DOCUMENTO.REQUERIDO";

    public static final String COMPROBANTE_NUMERO_REQUERIDO =
            "FACTUCORE.COMPROBANTE.NUMERO.REQUERIDO";

    public static final String COMPROBANTE_FECHA_EMISION_REQUERIDA =
            "FACTUCORE.COMPROBANTE.FECHA_EMISION.REQUERIDA";

    public static final String COMPROBANTE_ESTADO_PROCESO_REQUERIDO =
            "FACTUCORE.COMPROBANTE.ESTADO_PROCESO.REQUERIDO";

    public static final String VERSION_DOCUMENTO_XSD_DOCUMENTO_REQUERIDO =
            "FACTUCORE.VERSION_DOCUMENTO_XSD.DOCUMENTO.REQUERIDO";

    public static final String VERSION_DOCUMENTO_XSD_VERSION_REQUERIDA =
            "FACTUCORE.VERSION_DOCUMENTO_XSD.VERSION.REQUERIDA";

    public static final String VERSION_DOCUMENTO_XSD_VERSION_XSD_REQUERIDA =
            "FACTUCORE.VERSION_DOCUMENTO_XSD.VERSION_XSD.REQUERIDA";

    public static final String VERSION_DOCUMENTO_XSD_FECHA_INICIO_REQUERIDA =
            "FACTUCORE.VERSION_DOCUMENTO_XSD.FECHA_INICIO.REQUERIDA";

    public static final String VERSION_DOCUMENTO_XSD_RANGO_FECHAS_INVALIDO =
            "FACTUCORE.VERSION_DOCUMENTO_XSD.RANGO_FECHAS.INVALIDO";

    private MessageCodes() {
    }
}