package ec.dalara.factucore.domain.shared;

public final class MessageCodes {

    public static final String EMPRESA_RUC_REQUERIDO = "FACTUCORE.EMPRESA.RUC.REQUERIDO";
    public static final String EMPRESA_RAZON_SOCIAL_REQUERIDA = "FACTUCORE.EMPRESA.RAZON_SOCIAL.REQUERIDA";
    public static final String EMPRESA_DIRECCION_MATRIZ_REQUERIDA = "FACTUCORE.EMPRESA.DIRECCION_MATRIZ.REQUERIDA";
    public static final String RUC_REQUERIDO = "FACTUCORE.RUC.REQUERIDO";
    public static final String RUC_FORMATO_INVALIDO = "FACTUCORE.RUC.FORMATO_INVALIDO";
    public static final String ESTABLECIMIENTO_EMPRESA_REQUERIDA = "FACTUCORE.ESTABLECIMIENTO.EMPRESA.REQUERIDA";
    public static final String ESTABLECIMIENTO_CODIGO_REQUERIDO = "FACTUCORE.ESTABLECIMIENTO.CODIGO.REQUERIDO";
    public static final String PUNTO_EMISION_ESTABLECIMIENTO_REQUERIDO = "FACTUCORE.PUNTO_EMISION.ESTABLECIMIENTO.REQUERIDO";
    public static final String PUNTO_EMISION_CODIGO_REQUERIDO = "FACTUCORE.PUNTO_EMISION.CODIGO.REQUERIDO";
    public static final String SECUENCIAL_PUNTO_EMISION_REQUERIDO = "FACTUCORE.SECUENCIAL.PUNTO_EMISION.REQUERIDO";
    public static final String SECUENCIAL_CODIGO_DOCUMENTO_REQUERIDO = "FACTUCORE.SECUENCIAL.CODIGO_DOCUMENTO.REQUERIDO";
    public static final String SECUENCIAL_VALOR_INVALIDO = "FACTUCORE.SECUENCIAL.VALOR.INVALIDO";
    public static final String SECUENCIAL_LIMITE_ALCANZADO = "FACTUCORE.SECUENCIAL.LIMITE_ALCANZADO";
    public static final String NUMERO_COMPROBANTE_REQUERIDO = "FACTUCORE.NUMERO_COMPROBANTE.REQUERIDO";
    public static final String NUMERO_COMPROBANTE_FORMATO_INVALIDO = "FACTUCORE.NUMERO_COMPROBANTE.FORMATO_INVALIDO";
    public static final String CLAVE_ACCESO_BASE_LONGITUD_INVALIDA = "FACTUCORE.CLAVE_ACCESO.BASE.LONGITUD_INVALIDA";
    public static final String CLAVE_ACCESO_DATOS_REQUERIDOS = "FACTUCORE.CLAVE_ACCESO.DATOS.REQUERIDOS";
    public static final String CLAVE_ACCESO_FECHA_REQUERIDA = "FACTUCORE.CLAVE_ACCESO.FECHA.REQUERIDA";
    public static final String CLAVE_ACCESO_VALOR_REQUERIDO = "FACTUCORE.CLAVE_ACCESO.VALOR.REQUERIDO";
    public static final String CLAVE_ACCESO_FORMATO_NUMERICO_INVALIDO = "FACTUCORE.CLAVE_ACCESO.FORMATO.NUMERICO_INVALIDO";
    public static final String CLAVE_ACCESO_REQUERIDA = "FACTUCORE.CLAVE_ACCESO.REQUERIDA";
    public static final String CLAVE_ACCESO_FORMATO_INVALIDO = "FACTUCORE.CLAVE_ACCESO.FORMATO_INVALIDO";
    public static final String COMPROBANTE_EMPRESA_REQUERIDA = "FACTUCORE.COMPROBANTE.EMPRESA.REQUERIDA";
    public static final String COMPROBANTE_ESTABLECIMIENTO_REQUERIDO = "FACTUCORE.COMPROBANTE.ESTABLECIMIENTO.REQUERIDO";
    public static final String COMPROBANTE_PUNTO_EMISION_REQUERIDO = "FACTUCORE.COMPROBANTE.PUNTO_EMISION.REQUERIDO";
    public static final String COMPROBANTE_CODIGO_DOCUMENTO_REQUERIDO = "FACTUCORE.COMPROBANTE.CODIGO_DOCUMENTO_REQUERIDO";
    public static final String COMPROBANTE_NUMERO_REQUERIDO = "FACTUCORE.COMPROBANTE.NUMERO.REQUERIDO";
    public static final String COMPROBANTE_FECHA_EMISION_REQUERIDA = "FACTUCORE.COMPROBANTE.FECHA_EMISION.REQUERIDA";
    public static final String COMPROBANTE_ESTADO_PROCESO_REQUERIDO = "FACTUCORE.COMPROBANTE.ESTADO_PROCESO.REQUERIDO";
    public static final String COMPROBANTE_REQUEST_REQUERIDO = "FACTUCORE.COMPROBANTE.REQUEST.REQUERIDO";
    public static final String COMPROBANTE_TIPO_DOCUMENTO_REQUERIDO = "FACTUCORE.COMPROBANTE.TIPO_DOCUMENTO.REQUERIDO";
    public static final String COMPROBANTE_FECHA_INICIO_REQUERIDA = "FACTUCORE.COMPROBANTE.FECHA_INICIO.REQUERIDA";
    public static final String COMPROBANTE_DATOS_REQUERIDOS = "FACTUCORE.COMPROBANTE.DATOS.REQUERIDOS";
    public static final String COMPROBANTE_DATO_DUPLICADO = "FACTUCORE.COMPROBANTE.DATO.DUPLICADO";
    public static final String COMPROBANTE_DATO_KEY_REQUERIDA = "FACTUCORE.COMPROBANTE.DATO.KEY.REQUERIDA";
    public static final String COMPROBANTE_DEFINICION_NO_ENCONTRADA = "FACTUCORE.COMPROBANTE.DEFINICION.NO_ENCONTRADA";
    public static final String VERSION_DOCUMENTO_XSD_DOCUMENTO_REQUERIDO = "FACTUCORE.VERSION_DOCUMENTO_XSD.DOCUMENTO.REQUERIDO";
    public static final String VERSION_DOCUMENTO_XSD_VERSION_REQUERIDA = "FACTUCORE.VERSION_DOCUMENTO_XSD.VERSION.REQUERIDA";
    public static final String VERSION_DOCUMENTO_XSD_VERSION_XSD_REQUERIDA = "FACTUCORE.VERSION_DOCUMENTO_XSD.VERSION_XSD.REQUERIDA";
    public static final String VERSION_DOCUMENTO_XSD_FECHA_INICIO_REQUERIDA = "FACTUCORE.VERSION_DOCUMENTO_XSD.FECHA_INICIO.REQUERIDA";
    public static final String VERSION_DOCUMENTO_XSD_RANGO_FECHAS_INVALIDO = "FACTUCORE.VERSION_DOCUMENTO_XSD.RANGO_FECHAS.INVALIDO";
    public static final String SRI_XML_REQUERIDO = "FACTUCORE.SRI.XML.REQUERIDO";
    public static final String SRI_CLAVE_ACCESO_REQUERIDA = "FACTUCORE.SRI.CLAVE_ACCESO.REQUERIDA";
    public static final String SRI_AMBIENTE_REQUERIDO = "FACTUCORE.SRI.AMBIENTE.REQUERIDO";
    public static final String SRI_URL_RECEPCION_NO_CONFIGURADA = "FACTUCORE.SRI.URL.RECEPCION.NO_CONFIGURADA";
    public static final String SRI_URL_AUTORIZACION_NO_CONFIGURADA = "FACTUCORE.SRI.URL.AUTORIZACION.NO_CONFIGURADA";
    public static final String SRI_ERROR_COMUNICACION = "FACTUCORE.SRI.COMUNICACION.ERROR";
    public static final String SRI_RESPUESTA_INVALIDA = "FACTUCORE.SRI.RESPUESTA.INVALIDA";
    public static final String WORKFLOW_COMPROBANTE_REQUERIDO = "FACTUCORE.WORKFLOW.COMPROBANTE.REQUERIDO";
    public static final String WORKFLOW_RESULTADO_ETAPA_REQUERIDO = "FACTUCORE.WORKFLOW.RESULTADO_ETAPA.REQUERIDO";
    public static final String SECUENCIAL_NO_ENCONTRADO = "FACTUCORE.SECUENCIAL.NO_ENCONTRADO";
    public static final String FIRMA_CERTIFICADO_EMPRESA_REQUERIDA = "FACTUCORE.FIRMA.CERTIFICADO.EMPRESA.REQUERIDA";
    public static final String FIRMA_CERTIFICADO_PASSWORD_NO_CONFIGURADA = "FACTUCORE.FIRMA.CERTIFICADO.PASSWORD.NO_CONFIGURADA";
    public static final String FIRMA_XML_REQUERIDO = "FACTUCORE.FIRMA.XML.REQUERIDO";
    public static final String FIRMA_CERTIFICADO_VIGENTE_NO_ENCONTRADO = "FACTUCORE.FIRMA.CERTIFICADO.VIGENTE.NO_ENCONTRADO";

    private MessageCodes() {
    }
}